/*------------------------------------------------------------------------------------
5. MAGNITUDE ANALYSIS
-------------------------------------------------------------------------------------*/

------ Find total customers by countries

SELECT 
	country 
	,COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY 
	country 
ORDER BY 2 DESC;

------ Find total customers by gender

SELECT 
	gender 
	,COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY 2 DESC;

------ Find total customers by marital status

SELECT 
	marital_status
	,COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY marital_status
ORDER BY 2 DESC;

------ Find total number of products  by category

SELECT 
	category 
	,COUNT(product_key) AS total_number_products
FROM  gold.dim_products 
GROUP BY category
ORDER BY 2 DESC;

------ Find total products sold by category

SELECT 
	p.category 
	,COUNT(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY 
	p.category
ORDER BY 2 DESC;

------ Find the average costs in each category

SELECT 
	category 
	,AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY 
	category
ORDER BY 2 DESC;

------ Find the average selling price per product category

SELECT	
    DISTINCT category
		,AVG(f.price) AS average_price
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON f.product_key = p.product_key
GROUP BY  category; 

------ Find the total revenue generated for each category

SELECT 
	p.category 
	,SUM(f.sales) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY 
	p.category
ORDER BY 2 DESC;

------ Find the total items sold and total sales in each subcategory category

SELECT 
	DISTINCT subcategory
	,SUM(f.quantity) AS total_quantity_sold
	,SUM(f.sales) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products	p
ON f.product_key = p.product_key
GROUP BY 
	subcategory
ORDER BY 3 DESC

------ Find the total revenue generated by each customer

SELECT 
	c.customer_id
	,c.first_name
	,c.last_name
	,SUM(f.sales) AS total_sales 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_id
	,c.first_name
	,c.last_name
ORDER BY total_sales DESC;

------ What is the distribution of sold items accross countries

SELECT 
	 c.country
	,SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.country
ORDER BY total_quantity_sold DESC;
